sfdx-source/force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{0000}</displayFormat>
        <label>Job Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/objects/Job__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Jobs</relationshipLabel>
    <relationshipName>Jobs</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdx-source/force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Project Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdx-source/force-app/main/default/classes/services/JobsServiceImpl.cls
public inherited sharing class JobsServiceImpl implements IJobsService
{
    public void syncVendor(String task, List<Project__c> projectRecords)
    {
        fflib_ISObjectUnitOfWork uow = Application.UnitOfWork.newInstance();

        syncVendor(uow, task, projectRecords);

        uow.commitWork();
    }

    public void syncVendor(fflib_ISObjectUnitOfWork uow, String task, List<Project__c> projectRecords)
    {
        Set<Id> projectIds = getProjectsDomain(projectRecords).getRecordIds();
        Set<String> tasks = new Set<String> { task };
        Set<String> excludeJobStatuses = new Set<String>{ 'Cancelled', 'Completed' };

        List<Job__c> jobRecords =
            JobsSelector.newInstance().selectByProjectAndTaskAndNotInJobStatus(projectIds, tasks, excludeJobStatuses);

        String projectSpVendorfield = Projects.projectSpVendorByJobTask.get(task);

        for (Project__c projectRecord : projectRecords)
        {
            Id currentVendorId = (Id) projectRecord.get(projectSpVendorfield);

            uow.registerDirty(
                getJobsDomain(jobRecords.deepClone(true, true, true))
                    .filterByProject(projectRecord.Id)
                    .filterByNotInVendor(currentVendorId)
                    .setVendor(currentVendorId)
                    .getRecords()
            );
        }

    private IJobs getJobsDomain(List<Job__c> records)
    {
        return (IJobs) Application.Domain.newInstance(records, Schema.Job__c.SObjectType);
    }

    private IProjects getProjectsDomain(List<Project__c> records)
    {
        return (IProjects) Application.Domain.newInstance(records, Schema.Project__c.SObjectType);
    }
}